FROM centos:7 as download_mvn_dependencies

RUN yum install -y java-1.8.0-openjdk-devel \
    && yum clean all \
    && rm -rf /var/cache/yum/*

ENV JAVA_HOME=/etc/alternatives/java_sdk

RUN cd /opt \
    && curl -SL 'https://archive.apache.org/dist/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz' \
    | tar --extract --gzip \
    && ln --symbolic /opt/apache-maven-3.3.3/bin/mvn /usr/local/bin


WORKDIR /home/mpf/openmpf-projects

COPY openmpf/pom.xml openmpf/pom.xml
COPY openmpf/trunk/pom.xml openmpf/trunk/pom.xml
COPY openmpf/trunk/workflow-manager/pom.xml openmpf/trunk/workflow-manager/pom.xml
COPY openmpf/trunk/video-overlay/pom.xml openmpf/trunk/video-overlay/pom.xml
COPY openmpf/trunk/protobuf/pom.xml openmpf/trunk/protobuf/pom.xml
COPY openmpf/trunk/node-manager/pom.xml openmpf/trunk/node-manager/pom.xml
COPY openmpf/trunk/mpf-system-tests/pom.xml openmpf/trunk/mpf-system-tests/pom.xml
COPY openmpf/trunk/mpf-rest-client/pom.xml openmpf/trunk/mpf-rest-client/pom.xml
COPY openmpf/trunk/mpf-rest-api/pom.xml openmpf/trunk/mpf-rest-api/pom.xml
COPY openmpf/trunk/mpf-password-generator/pom.xml openmpf/trunk/mpf-password-generator/pom.xml
COPY openmpf/trunk/mpf-install/pom.xml openmpf/trunk/mpf-install/pom.xml
COPY openmpf/trunk/mpf-install/base-pom.xml openmpf/trunk/mpf-install/base-pom.xml
COPY openmpf/trunk/markup/pom.xml openmpf/trunk/markup/pom.xml
COPY openmpf/trunk/interop/pom.xml openmpf/trunk/interop/pom.xml
COPY openmpf/trunk/detection/executor/java/pom.xml openmpf/trunk/detection/executor/java/pom.xml

COPY openmpf/trunk/detection/test-components/java/pom.xml openmpf/trunk/detection/test-components/java/pom.xml
COPY openmpf/trunk/detection/test-components/java/JavaTestDetection/pom.xml openmpf/trunk/detection/test-components/java/JavaTestDetection/pom.xml

RUN cd openmpf && mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.1:collect
RUN cd openmpf && mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.1:go-offline --fail-never

COPY openmpf-java-component-sdk/pom.xml openmpf-java-component-sdk/pom.xml
COPY openmpf-java-component-sdk/detection/java-component-api/pom.xml openmpf-java-component-sdk/detection/java-component-api/pom.xml
COPY openmpf-java-component-sdk/detection/examples/pom.xml openmpf-java-component-sdk/detection/examples/pom.xml
COPY openmpf-java-component-sdk/detection/examples/HelloWorldComponent/pom.xml openmpf-java-component-sdk/detection/examples/HelloWorldComponent/pom.xml
COPY openmpf-java-component-sdk/detection/examples/AudioVideoComponent/pom.xml openmpf-java-component-sdk/detection/examples/AudioVideoComponent/pom.xml
COPY openmpf-java-component-sdk/detection/audio-video-utils/pom.xml openmpf-java-component-sdk/detection/audio-video-utils/pom.xml

RUN cd openmpf-java-component-sdk && mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.1:collect
RUN cd openmpf-java-component-sdk && mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.1:go-offline --fail-never


RUN cd openmpf && mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.1:get -Dartifact=org.codehaus.mojo:exec-maven-plugin:1.4.0

RUN rm -rf /root/.m2/repository/org/mitre/mpf


FROM scratch
COPY --from=download_mvn_dependencies /root/.m2 /root/.m2

