version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    command:
      - elasticsearch
      - -E
      - logger.level=error
    environment:
      discovery.type: single-node
    volumes:
      - elastic_search_data:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints:
          - node.role == manager

  kibana:
    image: ${REGISTRY}openmpf_kibana:${TAG}
    build: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      LOGGING_QUIET: 'true'
      KIBANA_DEFAULTAPPID: discover
      # Disable Kibana apps we don't use. Not all Kibana apps can be disabled.
      TELEMETRY_OPTIN: 'false'
      TELEMETRY_ENABLED: 'false'
      XPACK_APM_ENABLED: 'false'
      XPACK_CANVAS_ENABLED: 'false'
      XPACK_FLEET_ENABLED: 'false'
      XPACK_FLEET_AGENTS_ENABLED: 'false'
      XPACK_GRAPH_ENABLED: 'false'
      XPACK_INFRA_ENABLED: 'false'
      XPACK_MAPS_ENABLED: 'false'
      XPACK_ML_ENABLED: 'false'
      XPACK_MONITORING_ENABLED: 'false'
      XPACK_REPORTING_ENABLED: 'false'
      # Enable security yourself: https://www.elastic.co/guide/en/kibana/current/security-settings-kb.html
      XPACK_ROLLUP_ENABLED: 'false'
      XPACK_SECURITY_ENABLED: 'false'
      XPACK_SPACES_ENABLED: 'false'
      NEWSFEED_ENABLED: 'false'
      MONITORING_ENABLED: 'false'
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    deploy:
      placement:
        constraints:
          - node.role == manager

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.1
    command:
      # Allow filebeat's own logs to be collected
      - -e
      - -E
      - logging.level=warning
      - -E
      - 'filebeat.autodiscover.providers=[{type: docker, hints.enabled: true}]'
      - -E
      - output.elasticsearch.hosts=elasticsearch:9200
    # Need to be root to interact with Docker socket
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: global
    depends_on:
      - elasticsearch

  metricbeat:
    image: openmpf_metricbeat:latest
    build: metricbeat
    command:
      - -e
      - -E
      - logging.level=warning
    user: root
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      KIBANA_HOST: kibana:5601
    depends_on:
      - activemq
      - elasticsearch
      - kibana
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  elastic_search_data:
