#############################################################################
# NOTICE                                                                    #
#                                                                           #
# This software (or technical data) was produced for the U.S. Government    #
# under contract, and is subject to the Rights in Data-General Clause       #
# 52.227-14, Alt. IV (DEC 2007).                                            #
#                                                                           #
# Copyright 2019 The MITRE Corporation. All Rights Reserved.                #
#############################################################################

#############################################################################
# Copyright 2019 The MITRE Corporation                                      #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
#    http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################

# Use this file in conjunction with docker-compose.http.yml or
# docker-compose.https.yml.

version: '3.7'

services:
  mysql_database:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    # https://github.com/docker-library/mariadb/issues/113
    command: [
      '--wait_timeout=28800',
    ]
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - overlay
    deploy:
      placement:
        constraints:
          - node.role == manager

  activemq:
    image: ${REGISTRY}openmpf_active_mq:${TAG}
    build:
      context: ./active_mq
    environment:
      # Set which configuration files are used at runtime:
      - ACTIVE_MQ_PROFILE=${ACTIVE_MQ_PROFILE}
    ports:
      - "8161:8161"
    networks:
      - overlay

  redis:
    image: redis:latest
    networks:
      - overlay

  elk:
    image: ${REGISTRY}openmpf_elk:${TAG}
    build:
      context: ./elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    networks:
      - overlay

  workflow_manager:
    image: ${REGISTRY}openmpf_workflow_manager:${TAG}
    build:
      context: ./openmpf_runtime
      dockerfile: workflow_manager/Dockerfile
    depends_on:
      - mysql_database
      - redis
      - activemq
    restart: always
    environment:
      # The following line is needed to wait until the mySQL service is available:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - shared_data:/opt/mpf/share
    networks:
      - overlay
    deploy:
      placement:
        constraints:
          - node.role == manager

  node_manager:
    image: ${REGISTRY}openmpf_node_manager:${TAG}
    build:
      context: ./openmpf_runtime
      dockerfile: node_manager/Dockerfile
    volumes:
      - shared_data:/opt/mpf/share
    networks:
      - overlay
    deploy:
      mode: global

volumes:
  shared_data:
  mysql_data:

networks:
  overlay:
