#############################################################################
# NOTICE                                                                    #
#                                                                           #
# This software (or technical data) was produced for the U.S. Government    #
# under contract, and is subject to the Rights in Data-General Clause       #
# 52.227-14, Alt. IV (DEC 2007).                                            #
#                                                                           #
# Copyright 2020 The MITRE Corporation. All Rights Reserved.                #
#############################################################################

#############################################################################
# Copyright 2020 The MITRE Corporation                                      #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
#    http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################

version: '3.7'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mpf}
      POSTGRES_USER: ${POSTGRES_USER:-mpf}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.role == manager

  activemq:
    image: ${REGISTRY}openmpf_activemq:${TAG}
    build: activemq
    environment:
      # Set which configuration files are used at runtime:
      - ACTIVE_MQ_PROFILE=${ACTIVE_MQ_PROFILE}
    ports:
      - "8161:8161"

  redis:
    image: redis:alpine

  workflow-manager:
    image: ${REGISTRY}openmpf_workflow_manager:${TAG}
    build: workflow_manager
    depends_on:
      - db
      - redis
      - activemq
    ports:
      - "8080:8080"
    volumes:
      - shared_data:/opt/mpf/share
    deploy:
      placement:
        constraints:
          - node.role == manager

  markup:
    image: ${REGISTRY}openmpf_markup:${TAG}
    build: markup
    volumes:
      - shared_data:/opt/mpf/share
    deploy:
      mode: global

volumes:
  shared_data:
  db_data:
