FROM python_executor:latest

# Manually install packages here so they don't need to be re-installed every time the source code changes.
# RUN "$COMPONENT_VIRTUALENV/bin/pip" install --no-cache-dir 'tensorflow'

COPY . /home/mpf/component_src/

RUN /home/mpf/scripts/install-component.sh
